name: Datpixel
version: '${project.version}'
main: org.roguemc.roleplay.Roleplay
author: VirusDetected
description: Datpixel Core
depend: [Vault]
commands:
  roleplay:
    description: Opens the GUI for roleplays
    usage: /rp
  rp:
    description: Ape
    usage: /rpinvite
  emotes:
    description: This forces the command to be ran by console.
    usage: /cmd <command>
  noemotes:
    description: Blocks emotes.
    usage: /noemotes
  emotesreload:
    description: reloads emotes
    usage: /emotesreload
  suffix:
    description: ape
    usage: /suffix
  suffixclear:
    description: ape2
    usage: /suffixclear <player>